language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
  - "nightly"
# Fetch dependencies
before_install:
    - sudo apt-get -qq update
install:
    - sudo apt-get install -qq bind9-host
    - pip install -vr requirements.txt
# Run supybot-test
script:
# Weather and LastFM are hosted in their own repositories and tested separately.
  - supybot-test -c --plugins-dir=. --no-network --exclude=./LastFM --exclude=./Weather
notifications:
    email: false
matrix:
    fast_finish: true
    allow_failures:
        - python: "pypy"
        - python: "pypy3"
branches:
  except:
    - /^archive-.*$/
    - /^wip\/.*$/
